# ${-} are variables from Maven (pom.xml) which will be replaced after the build
name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}

# meta information for plugin managers
authors: [games647, frost-byte, 'https://github.com/frost-byte/TabChannelsX/graphs/contributors']
description: |
    ${project.description}
website: ${project.url}
dev-url: ${project.url}
api-version: 1.14

# Load after Protcollib for registering the packet listener
softdepend: [ProtocolLib]

commands:
    switchchannel:
        description: 'Switches the chat channel'
        aliases: [switch, channel]
        permission: ${project.artifactId}.command.switch

    private:
        description: 'Creates a private chat channel with your partner'
        aliases: [tell, pm]
        permission: ${project.artifactId}.command.private

    ${project.artifactId}:
        description: 'All relevant commands to interact with chat channels'
        aliases: [channel, tb]

    createchannel:
        description: 'Creates'
        aliases: [tb_createchannel]
        permission: ${project.artifactId}.command.create